services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - USER=localuser
      - PASS=localpassword
    volumes:
      - /c/Users/Chris/Documents/example.config:/userDefined.config
      - /c/Users/Chris/Documents/baseDirectory/:/baseDirectory/
