services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - USER=localuser
      - PASS=localpassword
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
    volumes:
      - /c/Documents/example.config:/userDefined.config
      - /c/Documents/baseDirectory/:/baseDirectory/
