name: Docker Build & Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chriszilla1123/channel-archive-server:latest
    - name: Build and push to latest
      uses: docker/build-push-action@v5
      if: github.ref == 'refs/heads/master'
      with:
        platforms: linux/amd64,linux/arm64,linux/arm
        push: true
        tags: |
          chriszilla1123/channelarchive.py:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
